cars:
  connection: postgres
  database: user_study
  name: cars_raw
  key: id

dermatology:
  connection: datafolder

housing:
  connection: datafolder
  key: id

iris:
  connection: datafolder

mushroom:
  connection: datafolder

sdss_random_sample:
  connection: postgres
  database: sdss
  name: sdss_random_sample
  key: objid
