cars:
  dataset:
    name: cars
    columns: "*"
  user:
    true_predicate: "height < 1.5 AND length < 5.0"
    max_iter: 100

housing:
  dataset:
    name: housing
    columns:
      - long
      - price
      - beds
      - pricesqrf
      - crime
      - population
      - income
  user:
    true_predicate: "long + price < 100000"
    max_iter: 100
  preprocessing:
    - "one hot encoding"
    - "standardize"

iris:
  dataset:
    name: iris
    columns:
      - sepal_length
      - sepal_width
  user:
    true_class: "Iris-setosa"
    max_iter: 50
  preprocessing:
    - "standardize"

mushroom:
  dataset:
    name: mushroom
    columns: "*"
  user:
    max_iter: 100
  preprocessing:
    - "one hot encoding"
    - "from binary to sign"

sdss_random_sample_test:
  dataset:
    name: sdss_random_sample
    columns:
      - rowc
      - colc
  user:
    true_predicate: "rowc + colc < 200"
    max_iter: 50

sdss_Q1.1:
  dataset:
    name: sdss_random_sample
    columns:
      - rowc
      - colc
  user:
    true_predicate: "rowc > 662.5 AND rowc < 702.5 AND colc > 991.5 AND colc < 1053.5"
    max_iter: 50
  preprocessing:
    - "standardize"

sdss_Q1.2:
  dataset:
    name: sdss_random_sample
    columns:
      - rowc
      - colc
  user:
    true_predicate: "rowc > 617.5 AND rowc < 747.5 AND colc > 925 AND colc < 1120"
    max_iter: 50

sdss_Q1.3:
  dataset:
    name: sdss_random_sample
    columns:
      - rowc
      - colc
  user:
    true_predicate: "rowc > 480 AND rowc < 885 AND colc > 719 AND colc < 1326"
    max_iter: 50

sdss_Q2.1:
  dataset:
    name: sdss_random_sample
    columns:
      - rowc
      - colc
  user:
    true_predicate: "(rowc - 682.5) * (rowc - 682.5) + (colc - 1022.5) * (colc - 1022.5) < 29 * 29"
    max_iter: 50

sdss_Q2.2:
  dataset:
    name: sdss_random_sample
    columns:
      - rowc
      - colc
  user:
    true_predicate: "(rowc - 682.5) * (rowc - 682.5) + (colc - 1022.5) * (colc - 1022.5) < 90 * 90"
    max_iter: 50

sdss_Q2.3:
  dataset:
    name: sdss_random_sample
    columns:
      - rowc
      - colc
  user:
    true_predicate: "(rowc - 682.5) * (rowc - 682.5) + (colc - 1022.5) * (colc - 1022.5) < 280 * 280"
    max_iter: 50

sdss_Q3.1:
  dataset:
    name: sdss_random_sample
    columns:
      - ra
      - dec
  user:
    true_predicate: "ra > 190 AND ra < 200 AND dec > 53 AND dec < 57"
    max_iter: 50

sdss_Q3.2:
  dataset:
    name: sdss_random_sample
    columns:
      - ra
      - dec
  user:
    true_predicate: "ra > 180 AND ra < 210 AND dec > 50 AND dec < 60"
    max_iter: 50

sdss_Q3.3:
  dataset:
    name: sdss_random_sample
    columns:
      - ra
      - dec
  user:
    true_predicate: "ra > 150 AND ra < 240 AND dec > 40 AND dec < 70"
    max_iter: 50
